# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: styletts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'styletts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estyletts.proto\x12\x0bstyletts.v1\"O\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12,\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1c.styletts.v1.SynthesisConfig\"\xd7\x01\n\x1cIncrementalSynthesizeRequest\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.styletts.v1.SynthesisConfigH\x00\x12\x14\n\ntext_chunk\x18\x02 \x01(\tH\x00\x12.\n\x06\x63\x61ncel\x18\x03 \x01(\x0b\x32\x1c.styletts.v1.CancelSynthesisH\x00\x12\x36\n\x0f\x66orce_synthesis\x18\x04 \x01(\x0b\x32\x1b.styletts.v1.ForceSynthesisH\x00\x42\t\n\x07\x63ontent\"C\n\x14IncrementalTextChunk\x12\x12\n\ntext_chunk\x18\x02 \x01(\t\x12\x17\n\x0f\x66orce_synthesis\x18\x03 \x01(\x08\"\x11\n\x0f\x43\x61ncelSynthesis\"\x10\n\x0e\x46orceSynthesis\"M\n\x0fSynthesisConfig\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\x05\"X\n\x12SynthesizeResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12.\n\nalignments\x18\x02 \x03(\x0b\x32\x1a.styletts.v1.WordAlignment\"?\n\rWordAlignment\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\x05\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\x05\x32\xa0\x02\n\x0fStyleTTSService\x12M\n\nSynthesize\x12\x1e.styletts.v1.SynthesizeRequest\x1a\x1f.styletts.v1.SynthesizeResponse\x12U\n\x10SynthesizeStream\x12\x1e.styletts.v1.SynthesizeRequest\x1a\x1f.styletts.v1.SynthesizeResponse0\x01\x12g\n\x15SynthesizeIncremental\x12).styletts.v1.IncrementalSynthesizeRequest\x1a\x1f.styletts.v1.SynthesizeResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'styletts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=31
  _globals['_SYNTHESIZEREQUEST']._serialized_end=110
  _globals['_INCREMENTALSYNTHESIZEREQUEST']._serialized_start=113
  _globals['_INCREMENTALSYNTHESIZEREQUEST']._serialized_end=328
  _globals['_INCREMENTALTEXTCHUNK']._serialized_start=330
  _globals['_INCREMENTALTEXTCHUNK']._serialized_end=397
  _globals['_CANCELSYNTHESIS']._serialized_start=399
  _globals['_CANCELSYNTHESIS']._serialized_end=416
  _globals['_FORCESYNTHESIS']._serialized_start=418
  _globals['_FORCESYNTHESIS']._serialized_end=434
  _globals['_SYNTHESISCONFIG']._serialized_start=436
  _globals['_SYNTHESISCONFIG']._serialized_end=513
  _globals['_SYNTHESIZERESPONSE']._serialized_start=515
  _globals['_SYNTHESIZERESPONSE']._serialized_end=603
  _globals['_WORDALIGNMENT']._serialized_start=605
  _globals['_WORDALIGNMENT']._serialized_end=668
  _globals['_STYLETTSSERVICE']._serialized_start=671
  _globals['_STYLETTSSERVICE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
