use super::Case;

pub(super) const CASES: &[Case] = &[
    Case {
        text: "He works for ABC Ltd. and sometimes for BCD Ltd. She works for ABC Co. and BCD Co. They work for ABC Corp. and BCD Corp.",
        expected: &[
            "He works for ABC Ltd. and sometimes for BCD Ltd.",
            "She works for ABC Co. and BCD Co.",
            "They work for ABC Corp. and BCD Corp.",
        ],
    },
    Case { text: "<bpt i=\"0\" type=\"bold\">&lt;b&gt;</bpt>J1.txt<ept i=\"1\">&lt;/b&gt;</ept>", expected: &["J1.txt"] },
    Case {
        text: "On Jan. 20, former Sen. Barack Obama became the 44th President of the U.S. Millions attended the Inauguration.",
        expected: &["On Jan. 20, former Sen. Barack Obama became the 44th President of the U.S.", "Millions attended the Inauguration."],
    },
    Case {
        text: "The U.K. Panel on enivronmental issues said it was true. Finally he left the U.K. He went to a new location.",
        expected: &["The U.K. Panel on enivronmental issues said it was true.", "Finally he left the U.K.", "He went to a new location."],
    },
    Case {
        text: "He left at 6 P.M. Travelers who didn't get the warning at 5 P.M. left later.",
        expected: &["He left at 6 P.M.", "Travelers who didn't get the warning at 5 P.M. left later."],
    },
    Case {
        text: "He left at 6 a.m. Travelers who didn't get the warning at 5 a.m. left later.",
        expected: &["He left at 6 a.m.", "Travelers who didn't get the warning at 5 a.m. left later."],
    },
    Case {
        text: "He left at 6 A.M. Travelers who didn't get the warning at 5 A.M. left later.",
        expected: &["He left at 6 A.M.", "Travelers who didn't get the warning at 5 A.M. left later."],
    },
    Case {
        text: "Hello World. My name is Jonas. What is your name? My name is Jonas. There it is! I found it. My name is Jonas E. Smith. Please turn to p. 55. Were Jane and co. at the party? They closed the deal with Pitt, Briggs & Co. at noon. Let's ask Jane and co. They should know. They closed the deal with Pitt, Briggs & Co. It closed yesterday. I can see Mt. Fuji from here. St. Michael's Church is on 5th st. near the light. That is JFK Jr.'s book. I visited the U.S.A. last year. I live in the E.U. How about you? I live in the U.S. How about you? I work for the U.S. Government in Virginia. I have lived in the U.S. for 20 years. She has $100.00 in her bag. She has $100.00. It is in her bag. He teaches science (He previously worked for 5 years as an engineer.) at the local University. Her email is Jane.Doe@example.com. I sent her an email. The site is: https://www.example.50.com/new-site/awesome_content.html. Please check it out. She turned to him, 'This is great.' she said. She turned to him, \"This is great.\" she said. She turned to him, \"This is great.\" She held the book out to show him. Hello!! Long time no see. Hello?? Who is there? Hello!? Is that you? Hello?! Is that you? 1.) The first item 2.) The second item 1.) The first item. 2.) The second item. 1) The first item 2) The second item 1) The first item. 2) The second item. 1. The first item 2. The second item 1. The first item. 2. The second item. • 9. The first item • 10. The second item ⁃9. The first item ⁃10. The second item a. The first item b. The second item c. The third list item \rIt was a cold \nnight in the city. features\ncontact manager\nevents, activities\n You can find it at N°. 1026.253.553. That is where the treasure is. She works at Yahoo! in the accounting department. We make a good team, you and I. Did you see Albert I. Jones yesterday? Thoreau argues that by simplifying one’s life, “the laws of the universe will appear less complex. . . .”. \"Bohr [...] used the analogy of parallel stairways [...]\" (Smith 55). If words are left off at the end of a sentence, and that is all that is omitted, indicate the omission with ellipsis marks (preceded and followed by a space) and then indicate the end of the sentence with a period . . . . Next sentence. I never meant that.... She left the store. I wasn’t really ... well, what I mean...see . . . what I'm saying, the thing is . . . I didn’t mean it. One further habit which was somewhat weakened . . . was that of combining words into self-interpreting compounds. . . . The practice was not abandoned. . . .",
        expected: &[
            "Hello World.",
            "My name is Jonas.",
            "What is your name?",
            "My name is Jonas.",
            "There it is!",
            "I found it.",
            "My name is Jonas E. Smith.",
            "Please turn to p. 55.",
            "Were Jane and co. at the party?",
            "They closed the deal with Pitt, Briggs & Co. at noon.",
            "Let's ask Jane and co.",
            "They should know.",
            "They closed the deal with Pitt, Briggs & Co.",
            "It closed yesterday.",
            "I can see Mt. Fuji from here.",
            "St. Michael's Church is on 5th st. near the light.",
            "That is JFK Jr.'s book.",
            "I visited the U.S.A. last year.",
            "I live in the E.U.",
            "How about you?",
            "I live in the U.S.",
            "How about you?",
            "I work for the U.S. Government in Virginia.",
            "I have lived in the U.S. for 20 years.",
            "She has $100.00 in her bag.",
            "She has $100.00.",
            "It is in her bag.",
            "He teaches science (He previously worked for 5 years as an engineer.) at the local University.",
            "Her email is Jane.Doe@example.com.",
            "I sent her an email.",
            "The site is: https://www.example.50.com/new-site/awesome_content.html.",
            "Please check it out.",
            "She turned to him, 'This is great.' she said.",
            "She turned to him, \"This is great.\" she said.",
            "She turned to him, \"This is great.\"",
            "She held the book out to show him.",
            "Hello!!",
            "Long time no see.",
            "Hello??",
            "Who is there?",
            "Hello!?",
            "Is that you?",
            "Hello?!",
            "Is that you?",
            "1.) The first item",
            "2.) The second item",
            "1.) The first item.",
            "2.) The second item.",
            "1) The first item",
            "2) The second item",
            "1) The first item.",
            "2) The second item.",
            "1. The first item",
            "2. The second item",
            "1. The first item.",
            "2. The second item.",
            "• 9. The first item",
            "• 10. The second item",
            "⁃9. The first item",
            "⁃10. The second item",
            "a. The first item",
            "b. The second item",
            "c. The third list item",
            "It was a cold night in the city.",
            "features",
            "contact manager",
            "events, activities",
            "You can find it at N°. 1026.253.553.",
            "That is where the treasure is.",
            "She works at Yahoo! in the accounting department.",
            "We make a good team, you and I.",
            "Did you see Albert I. Jones yesterday?",
            "Thoreau argues that by simplifying one’s life, “the laws of the universe will appear less complex. . . .”.",
            "\"Bohr [...] used the analogy of parallel stairways [...]\" (Smith 55).",
            "If words are left off at the end of a sentence, and that is all that is omitted, indicate the omission with ellipsis marks (preceded and followed by a space) and then indicate the end of the sentence with a period . . . .",
            "Next sentence.",
            "I never meant that....",
            "She left the store.",
            "I wasn’t really ... well, what I mean...see . . . what I'm saying, the thing is . . . I didn’t mean it.",
            "One further habit which was somewhat weakened . . . was that of combining words into self-interpreting compounds.",
            ". . . The practice was not abandoned. . . .",
        ],
    },
    Case {
        text: "His name is Mark E. Smith. a. here it is b. another c. one more\n They went to the store. It was John A. Smith. She was Jane B. Smith.",
        expected: &[
            "His name is Mark E. Smith.",
            "a. here it is",
            "b. another",
            "c. one more",
            "They went to the store.",
            "It was John A. Smith.",
            "She was Jane B. Smith.",
        ],
    },
    Case { text: "Hello{b^&gt;1&lt;b^} hello{b^>1<b^}.", expected: &["Hello hello."] },
    Case {
        text: "'Well?' thought Alice to herself, 'after such a fall as this, I shall think nothing of tumbling down stairs? How brave they'll all think me at home! Why, I wouldn't say anything about it, even if I fell off the top of the house!' (Which was very likely true.)",
        expected: &[
            "'Well?' thought Alice to herself, 'after such a fall as this, I shall think nothing of tumbling down stairs? How brave they'll all think me at home! Why, I wouldn't say anything about it, even if I fell off the top of the house!' (Which was very likely true.)",
        ],
    },
    Case {
        text: "Leave me alone! he yelled. I am in the U.S. Army. Charles (Ind.) said he.",
        expected: &["Leave me alone! he yelled.", "I am in the U.S. Army.", "Charles (Ind.) said he."],
    },
    Case {
        text: "She turned to him, “This is great.” She held the book out to show him.",
        expected: &["She turned to him, “This is great.”", "She held the book out to show him."],
    },
    Case {
        text: "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Header starts here\r////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
        expected: &["Header starts here"],
    },
    Case { text: "Hello World. \r\n Hello.", expected: &["Hello World.", "Hello."] },
    Case {
        text: "a) here it is b) another c) one more\n They went to the store. w) hello x) hello y) hello",
        expected: &["a) here it is", "b) another", "c) one more", "They went to the store.", "w) hello", "x) hello", "y) hello"],
    },
    Case { text: "Hello World. \\ r \\ nHello.", expected: &["Hello World.", "Hello."] },
    Case {
        text: "The nurse gave him the i.v. in his vein. She gave him the i.v. It was a great I.V. that she gave him. She gave him the I.V. It was night.",
        expected: &[
            "The nurse gave him the i.v. in his vein.",
            "She gave him the i.v.",
            "It was a great I.V. that she gave him.",
            "She gave him the I.V.",
            "It was night.",
        ],
    },
    Case {
        text: "(i) Hello world. \n(ii) Hello world.\n(iii) Hello world.\n(iv) Hello world.\n(v) Hello world.\n(vi) Hello world.",
        expected: &[
            "(i) Hello world.",
            "(ii) Hello world.",
            "(iii) Hello world.",
            "(iv) Hello world.",
            "(v) Hello world.",
            "(vi) Hello world.",
        ],
    },
    Case {
        text: "i) Hello world. \nii) Hello world.\niii) Hello world.\niv) Hello world.\nv) Hello world.\nvi) Hello world.",
        expected: &["i) Hello world.", "ii) Hello world.", "iii) Hello world.", "iv) Hello world.", "v) Hello world.", "vi) Hello world."],
    },
    Case {
        text: "(a) Hello world. (b) Hello world. (c) Hello world. (d) Hello world. (e) Hello world.\n(f) Hello world.",
        expected: &["(a) Hello world.", "(b) Hello world.", "(c) Hello world.", "(d) Hello world.", "(e) Hello world.", "(f) Hello world."],
    },
    Case {
        text: "(A) Hello world. \n(B) Hello world.\n(C) Hello world.\n(D) Hello world.\n(E) Hello world.\n(F) Hello world.",
        expected: &["(A) Hello world.", "(B) Hello world.", "(C) Hello world.", "(D) Hello world.", "(E) Hello world.", "(F) Hello world."],
    },
    Case {
        text: "A) Hello world. \nB) Hello world.\nC) Hello world.\nD) Hello world.\nE) Hello world.\nF) Hello world.",
        expected: &["A) Hello world.", "B) Hello world.", "C) Hello world.", "D) Hello world.", "E) Hello world.", "F) Hello world."],
    },
    Case {
        text: "The GmbH & Co. KG is a limited partnership with, typically, the sole general partner being a limited liability company.",
        expected: &[
            "The GmbH & Co. KG is a limited partnership with, typically, the sole general partner being a limited liability company.",
        ],
    },
    Case { text: "[?][footnoteRef:6] This is a footnote.", expected: &["[?][footnoteRef:6] This is a footnote."] },
    Case { text: "[15:  12:32]  [16:  firma? 13:28]", expected: &["[15:  12:32]  [16:  firma? 13:28]"] },
    Case {
        text: "\"It's a good thing that the water is really calm,\" I answered ironically.",
        expected: &["\"It's a good thing that the water is really calm,\" I answered ironically."],
    },
    Case {
        text: "December 31, 1988. Hello world. It's great! \nBorn April 05, 1989.",
        expected: &["December 31, 1988.", "Hello world.", "It's great!", "Born April 05, 1989."],
    },
    Case {
        text: "\"Dear, dear! How queer everything is to-day! And yesterday things went on just as usual. _Was_ I the same when I got up this morning? But if I'm not the same, the next question is, 'Who in the world am I?' Ah, _that's_ the great puzzle!\"",
        expected: &[
            "\"Dear, dear! How queer everything is to-day! And yesterday things went on just as usual. _Was_ I the same when I got up this morning? But if I'm not the same, the next question is, 'Who in the world am I?' Ah, _that's_ the great puzzle!\"",
        ],
    },
    Case {
        text: "Two began, in a low voice, \"Why, the fact is, you see, Miss, this here ought to have been a _red_ rose-tree, and we put a white one in by mistake; and, if the Queen was to find it out, we should all have our heads cut off, you know. So you see, Miss, we're doing our best, afore she comes, to--\" At this moment, Five, who had been anxiously looking across the garden, called out, \"The Queen! The Queen!\" and the three gardeners instantly threw themselves flat upon their faces.",
        expected: &[
            "Two began, in a low voice, \"Why, the fact is, you see, Miss, this here ought to have been a _red_ rose-tree, and we put a white one in by mistake; and, if the Queen was to find it out, we should all have our heads cut off, you know. So you see, Miss, we're doing our best, afore she comes, to--\"",
            "At this moment, Five, who had been anxiously looking across the garden, called out, \"The Queen! The Queen!\" and the three gardeners instantly threw themselves flat upon their faces.",
        ],
    },
    Case {
        text: "\"Dinah'll miss me very much to-night, I should think!\" (Dinah was the cat.) \"I hope they'll remember her saucer of milk at tea-time. Dinah, my dear, I wish you were down here with me!\"",
        expected: &[
            "\"Dinah'll miss me very much to-night, I should think!\"",
            "(Dinah was the cat.)",
            "\"I hope they'll remember her saucer of milk at tea-time. Dinah, my dear, I wish you were down here with me!\"",
        ],
    },
    Case {
        text: "Hello. 'This is a test of single quotes.' A new sentence.",
        expected: &["Hello.", "'This is a test of single quotes.'", "A new sentence."],
    },
    Case { text: "[A sentence in square brackets.]", expected: &["[A sentence in square brackets.]"] },
    Case { text: "(iii) List item number 3.", expected: &["(iii) List item number 3."] },
    Case { text: "(iii) List item number 3.", expected: &["(iii) List item number 3."] },
    Case { text: "Unbelievable??!?!", expected: &["Unbelievable??!?!"] },
    Case { text: "This abbreviation f.e. means for example.", expected: &["This abbreviation f.e. means for example."] },
    Case { text: "The med. staff here is very kind.", expected: &["The med. staff here is very kind."] },
    Case { text: "What did you order btw., she wondered.", expected: &["What did you order btw., she wondered."] },
];
